name: Terraform Deployment using GitHub Actions

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Plan
      run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \ -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \ -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \ -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \ -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
